Update MAINTAINERS info
fluxcd/helm-controller pull request #382
Opened 2021-12-14 13:32 UTC by dholbach

cc @seaneagan 

Signed-off-by: Daniel Holbach <daniel@weave.works>

2022-08-26 09:35 UTC, stefanprodan requested changes
@dholbach please move Sean to emeritus, he hasn't been actively involved with the project for over a year.

2022-08-26 09:45 UTC, dholbach commented
@fluxcd/core-maintainers please weigh in.

2022-08-26 09:45 UTC, hiddeco approved these changes

2022-08-26 09:56 UTC, stefanprodan approved these changes

2022-08-26 10:02 UTC, makkes approved these changes

2022-08-26 10:46 UTC, pjbgf approved these changes

2022-08-26 11:01 UTC, darkowlzz approved these changes

2022-08-31 10:10 UTC, relu approved these changes

2022-08-31 14:43 UTC, scottrigby approved these changes

2022-08-31 15:07 UTC, phillebaba approved these changes

2022-08-31 15:20 UTC, merged